# Generated by Django 5.2.1 on 2025-09-30 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('descripcion_trabajo', models.TextField()),
                ('observaciones_mecanico', models.TextField(blank=True)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_detallado', to='citas.cita')),
                ('mecanico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_realizados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_servicios', to='citas.vehiculo')),
            ],
            options={
                'verbose_name': 'Historial de Servicio',
                'verbose_name_plural': 'Historiales de Servicios',
                'ordering': ['-fecha_servicio'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoRecomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recomendacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('kilometraje_recomendado', models.PositiveIntegerField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('descripcion', models.TextField()),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('servicio_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tiposervicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_recomendados', to='citas.vehiculo')),
            ],
            options={
                'ordering': ['fecha_vencimiento', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('historial_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_utilizados', to='vehiculos.historialservicio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
