# Generated by Django 5.2.1 on 2025-05-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertainventario',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Alertas de Inventario'},
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='fecha_ultimo_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='notificado_por_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertainventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='alertainventario',
            name='tipo',
            field=models.CharField(choices=[('STOCK_BAJO', 'Stock Bajo'), ('STOCK_AGOTADO', 'Stock Agotado'), ('STOCK_CRITICO', 'Stock Crítico'), ('REPOSICION_URGENTE', 'Reposición Urgente')], max_length=20),
        ),
    ]
