# Generated by Django 5.2.1 on 2025-06-02 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('inventario', '0002_alter_alertainventario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteCarwash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BASICO', 'Lavado Básico'), ('COMPLETO', 'Lavado Completo'), ('PREMIUM', 'Lavado Premium'), ('DETALLADO', 'Detallado Completo')], max_length=10)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion_estimada', models.IntegerField(help_text='Duración en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('incluye_lavado_exterior', models.BooleanField(default=True)),
                ('incluye_lavado_interior', models.BooleanField(default=False)),
                ('incluye_aspirado', models.BooleanField(default=False)),
                ('incluye_encerado', models.BooleanField(default=False)),
                ('incluye_llantas', models.BooleanField(default=False)),
                ('incluye_motor', models.BooleanField(default=False)),
                ('incluye_proteccion_uv', models.BooleanField(default=False)),
                ('incluye_aromatizacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Paquetes de Carwash',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('factor_precio', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Vehículo',
            },
        ),
        migrations.CreateModel(
            name='CitaCarwash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_proceso', models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('LAVANDO', 'En Proceso de Lavado'), ('SECANDO', 'Secando'), ('FINALIZANDO', 'Finalizando Detalles'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado')], default='EN_ESPERA', max_length=15)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hora_inicio_proceso', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_proceso', models.DateTimeField(blank=True, null=True)),
                ('servicios_adicionales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carwash_detalle', to='citas.cita')),
                ('lavador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_asignadas', to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.paquetecarwash')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.tipovehiculo')),
            ],
            options={
                'verbose_name_plural': 'Citas de Carwash',
            },
        ),
        migrations.CreateModel(
            name='CalificacionCarwash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('cita_carwash', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='carwash.citacarwash')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones de Carwash',
            },
        ),
        migrations.CreateModel(
            name='ProductoCarwash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=3, max_digits=8)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cita_carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_utilizados', to='carwash.citacarwash')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name_plural': 'Productos utilizados en Carwash',
            },
        ),
    ]
